version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Navigating to frontend..."
      - cd frontend
      - echo "Installing dependencies..."
      - npm ci --legacy-peer-deps
  build:
    commands:
      - echo "Building React app..."
      # No need to cd again if you are already in the folder, 
      # but it doesn't hurt to be safe:
      - cd frontend
      - npm run build

artifacts:
  files:
    - '**/*'
  base-directory: frontend/dist
